CREATE TABLE IF NOT EXISTS employees (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    employee_id VARCHAR(30) NOT NULL UNIQUE,
    employee_name VARCHAR(120) NOT NULL,
    employee_password_hash VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS credit_risk_data (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    age FLOAT,
    education VARCHAR(80),
    gender VARCHAR(20),
    marital_status VARCHAR(40),
    net_monthly_income FLOAT,
    time_with_current_employer FLOAT,
    total_tradelines FLOAT,
    active_tradelines FLOAT,
    tradelines_opened_last_6m FLOAT,
    time_since_recent_enquiry FLOAT,
    approved_flag VARCHAR(20),
    credit_band VARCHAR(40),
    max_credit_amount FLOAT,
    income_bucket VARCHAR(40),
    risk_profile VARCHAR(40),
    source_file VARCHAR(255),
    created_at DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS credit_risk_dashboard_enhanced (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pct_tl_open_l6m FLOAT,
    pct_tl_closed_l6m FLOAT,
    total_tl_closed_l12m FLOAT,
    pct_tl_closed_l12m FLOAT,
    total_missed_payments FLOAT,
    cc_tradelines FLOAT,
    home_tradelines FLOAT,
    personal_loan_tradelines FLOAT,
    secured_tradelines FLOAT,
    unsecured_tradelines FLOAT,
    other_tradelines FLOAT,
    age_oldest_tradeline FLOAT,
    age_newest_tradeline FLOAT,
    time_since_recent_payment FLOAT,
    max_recent_delinquency_level FLOAT,
    delinquencies_6_12m FLOAT,
    times_60p_dpd FLOAT,
    standard_accounts_12m FLOAT,
    substandard_accounts FLOAT,
    substandard_accounts_6m FLOAT,
    substandard_accounts_12m FLOAT,
    doubtful_accounts FLOAT,
    doubtful_accounts_12m FLOAT,
    loss_accounts FLOAT,
    recent_delinquency_level FLOAT,
    cc_enquiries_12m FLOAT,
    pl_enquiries_12m FLOAT,
    time_since_recent_enquiry FLOAT,
    enquiries_l3m FLOAT,
    net_monthly_income FLOAT,
    time_with_current_employer FLOAT,
    has_credit_card BOOLEAN,
    has_personal_loan BOOLEAN,
    has_home_loan BOOLEAN,
    has_gold_loan BOOLEAN,
    education_code VARCHAR(40),
    approved_flag VARCHAR(20),
    marital_status VARCHAR(40),
    gender VARCHAR(20),
    last_product_enquiry VARCHAR(80),
    first_product_enquiry VARCHAR(80),
    income_bucket VARCHAR(40),
    risk_profile VARCHAR(40),
    source_file VARCHAR(255),
    created_at DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS fraud_detection_data (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    transaction_id VARCHAR(80) UNIQUE,
    transaction_timestamp DATETIME,
    transaction_type VARCHAR(80),
    amount FLOAT,
    origin_account VARCHAR(80),
    destination_account VARCHAR(80),
    old_balance_origin FLOAT,
    new_balance_origin FLOAT,
    old_balance_destination FLOAT,
    new_balance_destination FLOAT,
    location VARCHAR(120),
    risk_score FLOAT,
    risk_band VARCHAR(40),
    is_fraud BOOLEAN,
    source_file VARCHAR(255),
    created_at DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS prediction_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    employee_id VARCHAR(30) NOT NULL,
    module_name VARCHAR(50) NOT NULL,
    input_payload TEXT NOT NULL,
    prediction_label VARCHAR(80),
    prediction_score FLOAT,
    created_at DATETIME NOT NULL
);
